/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package centralmayorista;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
